name: Storybook Tests

on:
  pull_request:

jobs:
  test-storybook:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm i
      - name: Run Storybook tests
        run: npm run test-storybook:ci    
      - name: Generate LCOV report
        run: npx nyc report --reporter=lcov -t coverage/storybook --report-dir coverage/storybook
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with: 
          files: ./coverage/storybook/lcov.info